export const stack = [
  "Web Development",
  "Frontend",
  "Full-stack",
  "API", 
  "UI/UX Design",
  "AI/LLM Integrations",
  "DevOps",
  "Cloud",
  "Performance",
  "Testing",
  "Monitoring",
  "Logging",
  "Data Pipelines",
];
